version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
